### PR TITLE
essential fix for test  scatter reduce to pass

### PR DESCRIPTION
**Pull request by puririshi98**

### CODE REVIEW

**Review by rusty1s — APPROVED** [review]
Thanks for the PR, but I am unsure why we need this. Can you clarify?

**Comment by puririshi98** [comment]
```
__________________________ test_fused_scatter_reduce ___________________________
    @onlyCUDA
    @onlyTriton
    def test_fused_scatter_reduce():
        x = torch.randn(5, 4, device='cuda')
        index = torch.tensor([0, 1, 0, 1, 0], device='cuda')
    
>       out = fused_scatter_reduce(x, index, dim_size=2,
                                   reduce_list=['sum', 'mean'])
test/ops/test_scatter_reduce.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/dist-packages/pyg_lib-0.1.0-py3.8-linux-x86_64.egg/pyg_lib/ops/scatter_reduce.py:133: in fused_scatter_reduce
    fused_scatter_reduce_kernel[grid](
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = (tensor([[-0.1390, -0.5071,  0.1290, -0.1594],
        [-1.2358, -0.3644, -0.5571, -0.9715],
        [-0.3111, -0.7264...a:0'), tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0'), 4, 2, 20)
kwargs = {'BLOCK_SIZE': 256, 'REDUCE_LIST': ['sum', 'mean', 'none', 'none']}
    def launcher(*args, **kwargs):
>       return self.run(*args, grid=grid, **kwargs)
E       TypeError: fused_scatter_reduce_kernel() got an unexpected keyword argument 'REDUCE_LIST'
```

**Comment by puririshi98** [comment]
our CI gets the above failure, this should fix it

**Comment by rusty1s** [comment]
No, it does not expect capitalized names: https://github.com/pyg-team/pyg-lib/blob/master/pyg_lib/ops/scatter_reduce.py#L85

**Comment by rusty1s** [comment]
I need to revert this since the tests are now broken for me.

**Pull request merged**
